const express = require('express');
const router = express.Router();
const jwt = require('jsonwebtoken');
const Scholarship = require('../models/Scholarship');
const Student = require('../models/Student');
const Document = require('../models/Document');
const User = require('../models/User');
const { evaluateEligibility } = require('../services/eligibilityEngine');

// @route   POST /api/eligibility/check
// @desc    Run the 6-factor eligibility engine with custom or profile inputs
router.post('/check', async (req, res) => {
  try {
    let student = null;
    let documents = [];

    // Check if token provided
    if (req.headers.authorization && req.headers.authorization.startsWith('Bearer')) {
      try {
        const token = req.headers.authorization.split(' ')[1];
        const decoded = jwt.verify(token, process.env.JWT_SECRET || 'adivasisetu_super_secret_jwt_key_2026_tribal_welfare');
        student = await Student.findOne({ userId: decoded.id });
        if (student) {
          documents = await Document.find({ studentId: student._id });
        }
      } catch (e) {
        // guest check
      }
    }

    // Allow user overrides / manual testing
    const {
      state,
      category,
      tribalCommunity,
      educationLevel,
      course,
      percentageCgpa,
      annualFamilyIncome,
      documentsUploaded
    } = req.body;

    // Build effective mock student object for evaluation
    const effectiveStudent = {
      personalDetails: {
        state: state || student?.personalDetails?.state || 'Jharkhand',
        fullName: student?.personalDetails?.fullName || 'Student'
      },
      categoryDetails: {
        category: category || student?.categoryDetails?.category || 'Scheduled Tribe (ST)',
        tribalCommunity: tribalCommunity || student?.categoryDetails?.tribalCommunity || 'Tribal'
      },
      academicDetails: {
        educationLevel: educationLevel || student?.academicDetails?.educationLevel || 'Undergraduate (UG)',
        course: course || student?.academicDetails?.course || 'General',
        percentageCgpa: percentageCgpa !== undefined ? Number(percentageCgpa) : (student?.academicDetails?.percentageCgpa || 75)
      },
      financialDetails: {
        annualFamilyIncome: annualFamilyIncome !== undefined ? Number(annualFamilyIncome) : (student?.financialDetails?.annualFamilyIncome || 180000),
        incomeCertificateNumber: student?.financialDetails?.incomeCertificateNumber || 'INC-TEMP'
      }
    };

    let effectiveDocuments = documents;
    if (Array.isArray(documentsUploaded) && documentsUploaded.length > 0) {
      effectiveDocuments = documentsUploaded.map(docType => ({
        documentType: docType,
        status: 'Verified'
      }));
    } else if (documents.length === 0) {
      // Default sample documents for guest simulation
      effectiveDocuments = [
        { documentType: 'Aadhaar Card', status: 'Verified' },
        { documentType: 'ST Community Certificate', status: 'Verified' },
        { documentType: 'Income Certificate', status: 'Verified' }
      ];
    }

    // Fetch active scholarships
    const scholarships = await Scholarship.find({ status: 'Active' });

    // Evaluate each
    const evaluatedResults = scholarships.map(sch => {
      const evaluation = evaluateEligibility(effectiveStudent, sch, effectiveDocuments);
      return {
        scholarship: {
          _id: sch._id,
          scholarshipId: sch.scholarshipId,
          name: sch.name,
          scheme: sch.scheme,
          provider: sch.provider,
          description: sch.description,
          benefits: sch.benefits,
          deadline: sch.deadline,
          documents: sch.documents,
          eligibility: sch.eligibility
        },
        ...evaluation
      };
    });

    // Sort by match score descending
    evaluatedResults.sort((a, b) => b.matchScore - a.matchScore);

    // Grouping into Result Categories (Section 10)
    const highlyMatched = evaluatedResults.filter(r => r.matchCategory === 'Highly Matched');
    const potentialMatch = evaluatedResults.filter(r => r.matchCategory === 'Potential Match');
    const needsVerification = evaluatedResults.filter(r => r.matchCategory === 'Needs Verification');

    res.json({
      success: true,
      evaluatedCriteria: effectiveStudent,
      totalEvaluated: evaluatedResults.length,
      counts: {
        highlyMatched: highlyMatched.length,
        potentialMatch: potentialMatch.length,
        needsVerification: needsVerification.length
      },
      results: {
        highlyMatched,
        potentialMatch,
        needsVerification,
        all: evaluatedResults
      },
      disclaimer: 'Scores are generated by the AdivasiSetu Eligibility Algorithm using government-published norms. They serve as guidance and do not replace official government authority review.'
    });
  } catch (error) {
    console.error('Eligibility check error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
});

module.exports = router;
